/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * Crime Intelligence & Analytical Platform API — Karnataka State Police / SCRB
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * Returns server health status
 * @summary Health check
 */
export const HealthCheckResponse = zod.object({
  "status": zod.string()
})


/**
 * @summary List all districts with crime stats
 */
export const listDistrictsResponseRiskLevelMax = 5;



export const ListDistrictsResponseItem = zod.object({
  "id": zod.string(),
  "name": zod.string(),
  "lat": zod.number(),
  "lng": zod.number(),
  "crimeCount": zod.number(),
  "riskLevel": zod.number().min(1).max(listDistrictsResponseRiskLevelMax),
  "patrolCoverage": zod.number(),
  "population": zod.number(),
  "isBlindSpot": zod.boolean().optional(),
  "blindSpotReason": zod.string().nullish()
})
export const ListDistrictsResponse = zod.array(ListDistrictsResponseItem)


/**
 * @summary Get hotspot heatmap data, optionally filtered by district
 */
export const listHotspotsQueryTimeOfDayMin = 0;
export const listHotspotsQueryTimeOfDayMax = 23;



export const ListHotspotsQueryParams = zod.object({
  "districtId": zod.coerce.string().optional(),
  "timeOfDay": zod.coerce.number().min(listHotspotsQueryTimeOfDayMin).max(listHotspotsQueryTimeOfDayMax).optional(),
  "crimeType": zod.coerce.string().optional(),
  "blindSpot": zod.coerce.boolean().optional()
})

export const listHotspotsResponseIntensityMin = 0;
export const listHotspotsResponseIntensityMax = 1;



export const ListHotspotsResponseItem = zod.object({
  "id": zod.string().optional(),
  "lat": zod.number(),
  "lng": zod.number(),
  "intensity": zod.number().min(listHotspotsResponseIntensityMin).max(listHotspotsResponseIntensityMax),
  "districtId": zod.string(),
  "crimeType": zod.string(),
  "timeOfDay": zod.number(),
  "isAnomaly": zod.boolean().optional(),
  "stationName": zod.string().nullish()
})
export const ListHotspotsResponse = zod.array(ListHotspotsResponseItem)


/**
 * @summary List all cases
 */
export const ListCasesQueryParams = zod.object({
  "status": zod.enum(['open', 'under_review', 'closed']).optional(),
  "districtId": zod.coerce.string().optional(),
  "suspectId": zod.coerce.string().optional(),
  "patternId": zod.coerce.string().optional(),
  "limit": zod.coerce.number().optional()
})

export const ListCasesResponseItem = zod.object({
  "id": zod.string(),
  "title": zod.string(),
  "status": zod.enum(['open', 'under_review', 'closed']),
  "districtId": zod.string(),
  "districtName": zod.string(),
  "crimeType": zod.string(),
  "openedAt": zod.coerce.date(),
  "closedAt": zod.coerce.date().nullish(),
  "officerInCharge": zod.string(),
  "suspectIds": zod.array(zod.string()).optional(),
  "victimIds": zod.array(zod.string()).optional(),
  "patternId": zod.string().nullish(),
  "confidence": zod.number().optional()
})
export const ListCasesResponse = zod.array(ListCasesResponseItem)


/**
 * @summary Get a single case by ID
 */
export const GetCaseParams = zod.object({
  "id": zod.coerce.string()
})

export const GetCaseResponse = zod.object({
  "id": zod.string(),
  "title": zod.string(),
  "status": zod.enum(['open', 'under_review', 'closed']),
  "districtId": zod.string(),
  "districtName": zod.string(),
  "crimeType": zod.string(),
  "openedAt": zod.coerce.date(),
  "closedAt": zod.coerce.date().nullish(),
  "officerInCharge": zod.string(),
  "suspectIds": zod.array(zod.string()).optional(),
  "victimIds": zod.array(zod.string()).optional(),
  "patternId": zod.string().nullish(),
  "confidence": zod.number().optional()
}).and(zod.object({
  "summary": zod.string().optional(),
  "evidenceCount": zod.number().optional(),
  "linkedCaseIds": zod.array(zod.string()).optional()
}))


/**
 * @summary Aggregate case counts by status and district
 */
export const GetCaseSummaryResponse = zod.object({
  "total": zod.number(),
  "open": zod.number(),
  "underReview": zod.number(),
  "closed": zod.number(),
  "byDistrict": zod.array(zod.object({
  "districtId": zod.string(),
  "districtName": zod.string(),
  "count": zod.number()
}))
})


/**
 * @summary List suspects
 */
export const ListSuspectsQueryParams = zod.object({
  "caseId": zod.coerce.string().optional(),
  "districtId": zod.coerce.string().optional()
})

export const ListSuspectsResponseItem = zod.object({
  "id": zod.string(),
  "name": zod.string(),
  "alias": zod.string(),
  "age": zod.number(),
  "caseIds": zod.array(zod.string()),
  "districtId": zod.string(),
  "riskScore": zod.number(),
  "moSummary": zod.string(),
  "lastSeenAt": zod.coerce.date().nullish()
})
export const ListSuspectsResponse = zod.array(ListSuspectsResponseItem)


/**
 * @summary Get a single suspect by ID
 */
export const GetSuspectParams = zod.object({
  "id": zod.coerce.string()
})

export const GetSuspectResponse = zod.object({
  "id": zod.string(),
  "name": zod.string(),
  "alias": zod.string(),
  "age": zod.number(),
  "caseIds": zod.array(zod.string()),
  "districtId": zod.string(),
  "riskScore": zod.number(),
  "moSummary": zod.string(),
  "lastSeenAt": zod.coerce.date().nullish()
})


/**
 * @summary List victims
 */
export const ListVictimsQueryParams = zod.object({
  "caseId": zod.coerce.string().optional()
})

export const ListVictimsResponseItem = zod.object({
  "id": zod.string(),
  "initials": zod.string(),
  "age": zod.number(),
  "caseIds": zod.array(zod.string()),
  "districtId": zod.string()
})
export const ListVictimsResponse = zod.array(ListVictimsResponseItem)


/**
 * @summary Get all knowledge graph nodes
 */
export const ListGraphNodesQueryParams = zod.object({
  "caseId": zod.coerce.string().optional(),
  "districtId": zod.coerce.string().optional(),
  "patternId": zod.coerce.string().optional(),
  "timeIndex": zod.coerce.number().optional()
})

export const ListGraphNodesResponseItem = zod.object({
  "id": zod.string(),
  "type": zod.enum(['suspect', 'victim', 'location', 'case']),
  "label": zod.string(),
  "x": zod.number(),
  "y": zod.number(),
  "timeIndex": zod.number(),
  "moSummary": zod.string().nullish(),
  "linkedCaseIds": zod.array(zod.string()).optional(),
  "riskScore": zod.number().nullish()
})
export const ListGraphNodesResponse = zod.array(ListGraphNodesResponseItem)


/**
 * @summary Get all knowledge graph edges
 */
export const ListGraphEdgesQueryParams = zod.object({
  "caseId": zod.coerce.string().optional(),
  "districtId": zod.coerce.string().optional(),
  "patternId": zod.coerce.string().optional(),
  "timeIndex": zod.coerce.number().optional()
})

export const ListGraphEdgesResponseItem = zod.object({
  "id": zod.string(),
  "source": zod.string(),
  "target": zod.string(),
  "label": zod.string(),
  "timeIndex": zod.number(),
  "strength": zod.number().optional()
})
export const ListGraphEdgesResponse = zod.array(ListGraphEdgesResponseItem)


/**
 * @summary List behavioral pattern clusters (MO clusters)
 */
export const ListPatternsResponseItem = zod.object({
  "id": zod.string(),
  "label": zod.string(),
  "description": zod.string(),
  "confidence": zod.number(),
  "caseCount": zod.number(),
  "matchedCaseIds": zod.array(zod.string()),
  "sparkline": zod.array(zod.number()),
  "districtIds": zod.array(zod.string()).optional()
})
export const ListPatternsResponse = zod.array(ListPatternsResponseItem)


/**
 * @summary Get a single pattern with matched case IDs
 */
export const GetPatternParams = zod.object({
  "id": zod.coerce.string()
})

export const GetPatternResponse = zod.object({
  "id": zod.string(),
  "label": zod.string(),
  "description": zod.string(),
  "confidence": zod.number(),
  "caseCount": zod.number(),
  "matchedCaseIds": zod.array(zod.string()),
  "sparkline": zod.array(zod.number()),
  "districtIds": zod.array(zod.string()).optional()
})


/**
 * @summary Get dashboard analytics — trend data, anomaly stats, risk forecast
 */
export const getDashboardAnalyticsResponseRiskForecastItemRiskLevelMax = 5;



export const GetDashboardAnalyticsResponse = zod.object({
  "anomalyStats": zod.array(zod.object({
  "label": zod.string(),
  "value": zod.number(),
  "delta": zod.number(),
  "isAnomaly": zod.boolean(),
  "unit": zod.string().nullish()
})),
  "activeCaseCount": zod.number(),
  "criticalAlertCount": zod.number(),
  "solvedThisMonth": zod.number(),
  "riskForecast": zod.array(zod.object({
  "districtId": zod.string(),
  "districtName": zod.string(),
  "riskLevel": zod.number().min(1).max(getDashboardAnalyticsResponseRiskForecastItemRiskLevelMax),
  "trend": zod.enum(['up', 'flat', 'down'])
}))
})


/**
 * @summary Get crime trend series data for recharts
 */
export const GetCrimeTrendQueryParams = zod.object({
  "districtId": zod.coerce.string().optional(),
  "months": zod.coerce.number().optional()
})

export const GetCrimeTrendResponseItem = zod.object({
  "month": zod.string(),
  "crimeCount": zod.number(),
  "historicalAverage": zod.number(),
  "districtId": zod.string()
})
export const GetCrimeTrendResponse = zod.array(GetCrimeTrendResponseItem)


/**
 * @summary Get early warning system alerts
 */
export const ListAlertsQueryParams = zod.object({
  "read": zod.coerce.boolean().optional(),
  "severity": zod.enum(['critical', 'high', 'medium', 'low']).optional()
})

export const ListAlertsResponseItem = zod.object({
  "id": zod.string(),
  "title": zod.string(),
  "districtId": zod.string(),
  "districtName": zod.string(),
  "severity": zod.enum(['critical', 'high', 'medium', 'low']),
  "timestamp": zod.coerce.date(),
  "read": zod.boolean(),
  "message": zod.string(),
  "linkedCaseIds": zod.array(zod.string()).optional()
})
export const ListAlertsResponse = zod.array(ListAlertsResponseItem)


/**
 * @summary Get per-district risk forecast for the coming week
 */
export const getRiskForecastResponseRiskLevelMax = 5;



export const GetRiskForecastResponseItem = zod.object({
  "districtId": zod.string(),
  "districtName": zod.string(),
  "riskLevel": zod.number().min(1).max(getRiskForecastResponseRiskLevelMax),
  "trend": zod.enum(['up', 'flat', 'down'])
})
export const GetRiskForecastResponse = zod.array(GetRiskForecastResponseItem)


/**
 * @summary Get evidence items for a case
 */
export const GetCaseEvidenceParams = zod.object({
  "id": zod.coerce.string()
})

export const GetCaseEvidenceResponseItem = zod.object({
  "id": zod.string(),
  "caseId": zod.string(),
  "type": zod.enum(['document', 'image', 'audio', 'video', 'forensic', 'testimony', 'digital']),
  "label": zod.string(),
  "timestamp": zod.coerce.date(),
  "confidence": zod.number(),
  "verified": zod.boolean(),
  "notes": zod.string().nullish()
})
export const GetCaseEvidenceResponse = zod.array(GetCaseEvidenceResponseItem)


/**
 * @summary Get timeline events for a case
 */
export const GetCaseTimelineParams = zod.object({
  "id": zod.coerce.string()
})

export const GetCaseTimelineResponseItem = zod.object({
  "id": zod.string(),
  "caseId": zod.string(),
  "timestamp": zod.coerce.date(),
  "title": zod.string(),
  "description": zod.string(),
  "type": zod.enum(['incident', 'arrest', 'evidence_collected', 'witness_statement', 'court', 'update', 'alert']),
  "officerId": zod.string().nullish(),
  "evidenceIds": zod.array(zod.string()).optional()
})
export const GetCaseTimelineResponse = zod.array(GetCaseTimelineResponseItem)


/**
 * @summary Get bias audit data — closure rates and resource allocation by district/demographic
 */
export const GetBiasAuditResponse = zod.object({
  "generatedAt": zod.coerce.date(),
  "buckets": zod.array(zod.object({
  "label": zod.string(),
  "closureRate": zod.number(),
  "resourceAllocation": zod.number(),
  "caseCount": zod.number(),
  "flagged": zod.boolean().optional()
})),
  "disparity": zod.object({
  "detected": zod.boolean(),
  "severity": zod.enum(['none', 'low', 'moderate', 'high']),
  "description": zod.string(),
  "recommendation": zod.string()
})
})


/**
 * @summary Get officer access log for trust & identity module
 */
export const ListAccessLogQueryParams = zod.object({
  "limit": zod.coerce.number().optional()
})

export const ListAccessLogResponseItem = zod.object({
  "id": zod.string(),
  "officerId": zod.string(),
  "officerName": zod.string(),
  "action": zod.string(),
  "timestamp": zod.coerce.date(),
  "verificationStatus": zod.enum(['verified', 'pending', 'failed']),
  "blockRef": zod.string()
})
export const ListAccessLogResponse = zod.array(ListAccessLogResponseItem)


/**
 * @summary Get current ledger/blockchain sync status
 */
export const GetLedgerStatusResponse = zod.object({
  "state": zod.enum(['synced', 'verifying', 'integrity_alert']),
  "blockHeight": zod.number(),
  "lastBlockHash": zod.string(),
  "lastAnchoredAt": zod.coerce.date()
})


