/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * Crime Intelligence & Analytical Platform API — Karnataka State Police / SCRB
 * OpenAPI spec version: 0.1.0
 */
import type { AlertSeverity } from './alertSeverity';

export interface Alert {
  id: string;
  title: string;
  districtId: string;
  districtName: string;
  severity: AlertSeverity;
  timestamp: Date;
  read: boolean;
  message: string;
  linkedCaseIds?: string[];
}
