/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * Crime Intelligence & Analytical Platform API — Karnataka State Police / SCRB
 * OpenAPI spec version: 0.1.0
 */

export interface BehavioralPattern {
  id: string;
  label: string;
  description: string;
  confidence: number;
  caseCount: number;
  matchedCaseIds: string[];
  sparkline: number[];
  districtIds?: string[];
}
