/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * Crime Intelligence & Analytical Platform API — Karnataka State Police / SCRB
 * OpenAPI spec version: 0.1.0
 */

export type BiasDisparitySeverity = typeof BiasDisparitySeverity[keyof typeof BiasDisparitySeverity];


export const BiasDisparitySeverity = {
  none: 'none',
  low: 'low',
  moderate: 'moderate',
  high: 'high',
} as const;
