/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * Crime Intelligence & Analytical Platform API — Karnataka State Police / SCRB
 * OpenAPI spec version: 0.1.0
 */
import type { BiasAuditBucket } from './biasAuditBucket';
import type { BiasDisparity } from './biasDisparity';

export interface BiasAudit {
  generatedAt: Date;
  buckets: BiasAuditBucket[];
  disparity: BiasDisparity;
}
