/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * Crime Intelligence & Analytical Platform API — Karnataka State Police / SCRB
 * OpenAPI spec version: 0.1.0
 */
import type { CaseStatus } from './caseStatus';

export interface Case {
  id: string;
  title: string;
  status: CaseStatus;
  districtId: string;
  districtName: string;
  crimeType: string;
  openedAt: Date;
  /** @nullable */
  closedAt?: Date | null;
  officerInCharge: string;
  suspectIds?: string[];
  victimIds?: string[];
  /** @nullable */
  patternId?: string | null;
  confidence?: number;
}
