/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * Crime Intelligence & Analytical Platform API — Karnataka State Police / SCRB
 * OpenAPI spec version: 0.1.0
 */
import type { AnomalyStat } from './anomalyStat';
import type { RiskForecast } from './riskForecast';

export interface DashboardAnalytics {
  anomalyStats: AnomalyStat[];
  activeCaseCount: number;
  criticalAlertCount: number;
  solvedThisMonth: number;
  riskForecast: RiskForecast[];
}
