/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * Crime Intelligence & Analytical Platform API — Karnataka State Police / SCRB
 * OpenAPI spec version: 0.1.0
 */

export interface District {
  id: string;
  name: string;
  lat: number;
  lng: number;
  crimeCount: number;
  /**
     * @minimum 1
     * @maximum 5
     */
  riskLevel: number;
  patrolCoverage: number;
  population: number;
  isBlindSpot?: boolean;
  /** @nullable */
  blindSpotReason?: string | null;
}
