/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * Crime Intelligence & Analytical Platform API — Karnataka State Police / SCRB
 * OpenAPI spec version: 0.1.0
 */

export type EvidenceItemType = typeof EvidenceItemType[keyof typeof EvidenceItemType];


export const EvidenceItemType = {
  document: 'document',
  image: 'image',
  audio: 'audio',
  video: 'video',
  forensic: 'forensic',
  testimony: 'testimony',
  digital: 'digital',
} as const;
