/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * Crime Intelligence & Analytical Platform API — Karnataka State Police / SCRB
 * OpenAPI spec version: 0.1.0
 */
import type { EvidenceItemType } from './evidenceItemType';

export interface EvidenceItem {
  id: string;
  caseId: string;
  type: EvidenceItemType;
  label: string;
  timestamp: Date;
  confidence: number;
  verified: boolean;
  /** @nullable */
  notes?: string | null;
}
