/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * Crime Intelligence & Analytical Platform API — Karnataka State Police / SCRB
 * OpenAPI spec version: 0.1.0
 */
import type { GraphNodeType } from './graphNodeType';

export interface GraphNode {
  id: string;
  type: GraphNodeType;
  label: string;
  x: number;
  y: number;
  timeIndex: number;
  /** @nullable */
  moSummary?: string | null;
  linkedCaseIds?: string[];
  /** @nullable */
  riskScore?: number | null;
}
