/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * Crime Intelligence & Analytical Platform API — Karnataka State Police / SCRB
 * OpenAPI spec version: 0.1.0
 */

export type GraphNodeType = typeof GraphNodeType[keyof typeof GraphNodeType];


export const GraphNodeType = {
  suspect: 'suspect',
  victim: 'victim',
  location: 'location',
  case: 'case',
} as const;
