/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * Crime Intelligence & Analytical Platform API — Karnataka State Police / SCRB
 * OpenAPI spec version: 0.1.0
 */

export interface HotspotPoint {
  id?: string;
  lat: number;
  lng: number;
  /**
     * @minimum 0
     * @maximum 1
     */
  intensity: number;
  districtId: string;
  crimeType: string;
  timeOfDay: number;
  isAnomaly?: boolean;
  /** @nullable */
  stationName?: string | null;
}
