/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * Crime Intelligence & Analytical Platform API — Karnataka State Police / SCRB
 * OpenAPI spec version: 0.1.0
 */
import type { LedgerStatusState } from './ledgerStatusState';

export interface LedgerStatus {
  state: LedgerStatusState;
  blockHeight: number;
  lastBlockHash: string;
  lastAnchoredAt: Date;
}
