/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * Crime Intelligence & Analytical Platform API — Karnataka State Police / SCRB
 * OpenAPI spec version: 0.1.0
 */

export type ListCasesStatus = typeof ListCasesStatus[keyof typeof ListCasesStatus];


export const ListCasesStatus = {
  open: 'open',
  under_review: 'under_review',
  closed: 'closed',
} as const;
