/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * Crime Intelligence & Analytical Platform API — Karnataka State Police / SCRB
 * OpenAPI spec version: 0.1.0
 */
import type { ListCasesStatus } from './listCasesStatus';

export type ListCasesParams = {
status?: ListCasesStatus;
districtId?: string;
suspectId?: string;
patternId?: string;
limit?: number;
};
