/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * Crime Intelligence & Analytical Platform API — Karnataka State Police / SCRB
 * OpenAPI spec version: 0.1.0
 */

export type ListHotspotsParams = {
districtId?: string;
/**
 * @minimum 0
 * @maximum 23
 */
timeOfDay?: number;
crimeType?: string;
blindSpot?: boolean;
};
