/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * Crime Intelligence & Analytical Platform API — Karnataka State Police / SCRB
 * OpenAPI spec version: 0.1.0
 */
import type { RiskForecastTrend } from './riskForecastTrend';

export interface RiskForecast {
  districtId: string;
  districtName: string;
  /**
     * @minimum 1
     * @maximum 5
     */
  riskLevel: number;
  trend: RiskForecastTrend;
}
