/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * Crime Intelligence & Analytical Platform API — Karnataka State Police / SCRB
 * OpenAPI spec version: 0.1.0
 */

export type RiskForecastTrend = typeof RiskForecastTrend[keyof typeof RiskForecastTrend];


export const RiskForecastTrend = {
  up: 'up',
  flat: 'flat',
  down: 'down',
} as const;
