/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * Crime Intelligence & Analytical Platform API — Karnataka State Police / SCRB
 * OpenAPI spec version: 0.1.0
 */
import type { TimelineEventType } from './timelineEventType';

export interface TimelineEvent {
  id: string;
  caseId: string;
  timestamp: Date;
  title: string;
  description: string;
  type: TimelineEventType;
  /** @nullable */
  officerId?: string | null;
  evidenceIds?: string[];
}
