/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * Crime Intelligence & Analytical Platform API — Karnataka State Police / SCRB
 * OpenAPI spec version: 0.1.0
 */

export type TimelineEventType = typeof TimelineEventType[keyof typeof TimelineEventType];


export const TimelineEventType = {
  incident: 'incident',
  arrest: 'arrest',
  evidence_collected: 'evidence_collected',
  witness_statement: 'witness_statement',
  court: 'court',
  update: 'update',
  alert: 'alert',
} as const;
